README.md
lib/brainstem/presenter.rb
lib/brainstem/presenter_collection.rb
spec/brainstem/presenter_collection_spec.rb
spec/brainstem/presenter_spec.rb
spec/spec_helpers/db.rb

fix reflection for AR => 4.2

---

README.md

@cantino just a few minor typos I noticed.

Some minor typo fixes

---

lib/brainstem/presenter_collection.rb

@bennapp we forgot to submit this.

sort results in ruby for efficiency

---

lib/brainstem/presenter_collection.rb

Now that queries are split between plucking IDs and actual records, when paginating and sorting the kind of SQL generated for plucking IDs looks something like this:
```
SELECT  DISTINCT posts.id FROM "posts"  ORDER BY posts.title asc LIMIT 20 OFFSET 0
```
Postgres complains unless you include the column you're ordering by in the select:
```
ActiveRecord::StatementInvalid:
PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: SELECT  DISTINCT posts.id FROM "posts"  ORDER BY posts.title asc...
^
: SELECT  DISTINCT posts.id FROM "posts"  ORDER BY posts.title asc LIMIT 20 OFFSET 0
```
This commit adds the calculated sort name to the query when plucking IDs to appease Postgres (or any other database that complains similarly)

Only optimize queries by plucking IDs first for MySQL

---

README.md

Highlight the JS in the README

---

lib/brainstem/presenter.rb
lib/brainstem/presenter_validator.rb
spec/brainstem/presenter_spec.rb
spec/brainstem/presenter_validator_spec.rb

@robyurkowski mind reviewing / refactoring this a bit?
Hopefully a good introduction to a piece of the new Brainstem.

PresenterValidator handles more complex preloads; smarter preload de-duping when loading models

---

lib/brainstem/concerns/presenter_dsl.rb
lib/brainstem/dsl/associations_block.rb
lib/brainstem/dsl/base_block.rb
lib/brainstem/dsl/conditionals_block.rb
lib/brainstem/dsl/configuration.rb
lib/brainstem/dsl/fields_block.rb
lib/brainstem/preloader.rb
lib/brainstem/presenter.rb
spec/brainstem/preloader_spec.rb
spec/brainstem/presenter_spec.rb

I need to add one more fix here before this is merged (missing a test for when there are no valid preloads), but I think this is a reasonable attempt at removing some of the complexity of the presenter into an appropriate collaborator.

Refactor presenter preload

---

README.md
lib/brainstem/concerns/error_presentation.rb
lib/brainstem/controller_methods.rb
spec/brainstem/concerns/error_presentation_spec.rb

@shirish-pampoorickal, @plainprogrammer and I extracted these into Brainstem.
/cc @naiyt

Add error presentation helpers to Brainstem

---

README.md
lib/brainstem/dsl/field.rb
lib/brainstem/presenter.rb
lib/brainstem/presenter_collection.rb
spec/brainstem/dsl/field_spec.rb
spec/brainstem/presenter_collection_spec.rb
spec/brainstem/presenter_spec.rb
spec/spec_helpers/presenters.rb

Add the concept of optional fields, requested with an optional_fields param.

Add Optional Fields to Presenters

---

lib/brainstem/api_docs/builder.rb

@robyurkowski, this seems to work.  Did we miss anything?

Use the Optional Concern

---

README.md

Document apply_default_filters

---

lib/brainstem/api_docs/formatters/markdown/endpoint_formatter.rb
spec/brainstem/api_docs/formatters/markdown/endpoint_formatter_spec.rb

@robyurkowski, this looks better to us.

Only render the Data Model section when one has been provided

---

lib/brainstem/api_docs/formatters/markdown/presenter_formatter.rb
spec/brainstem/api_docs/formatters/markdown/presenter_formatter_spec.rb

@robyurkowski Appreciate a look

Shift the default sort order to the top and otherwise make alphabetical

---

lib/brainstem/api_docs/formatters/markdown/presenter_formatter.rb
spec/brainstem/api_docs/formatters/markdown/presenter_formatter_spec.rb

@robyurkowski Appreciate a look

Tabulate associations

---

lib/brainstem/presenter_collection.rb
spec/brainstem/presenter_collection_spec.rb

Useful for preloading data in an ERB partial
TODO
-
@cantino @rogerneel

Refactor structuring JSON response into own method for reusability

---

README.md

@shirish-pampoorickal LGTM? I forgot to update the README with the previous change.

Update readme with precedence change

---

CHANGELOG.md
lib/brainstem/version.rb

@shirish-pampoorickal, this bumps the version and updates the changelog in prep for doing a 1.0.0.pre.1 release.

Release 1.0.0.pre.1

---

CHANGELOG.md

Add missing markdown formatting

---

CHANGELOG.md
lib/brainstem/version.rb

added changelog for new enhancements and bugfixes for Brainstem 2.1.0

---

.gitignore
.travis.yml
CHANGELOG.md
Gemfile.lock
README.md
brainstem.gemspec
gemfiles/activerecord4_2.gemfile
gemfiles/activerecord4_2.gemfile.lock
gemfiles/activerecord5_0.gemfile
gemfiles/activerecord5_0.gemfile.lock
gemfiles/activerecord5_1.gemfile
gemfiles/activerecord5_1.gemfile.lock
gemfiles/activerecord5_2.gemfile
gemfiles/activerecord5_2.gemfile.lock
gemfiles/activerecord6_0.gemfile
gemfiles/activerecord6_0.gemfile.lock
lib/brainstem/api_docs.rb
lib/brainstem/query_strategies/base_strategy.rb
lib/brainstem/version.rb
spec/brainstem/api_docs/endpoint_spec.rb
spec/brainstem/controller_methods_spec.rb
spec/brainstem/presenter_spec.rb
spec/brainstem/query_strategies/filter_and_search_spec.rb
spec/brainstem/query_strategies/filter_or_search_spec.rb

- Drop support for version of Rails below 4.2
- Update travis config to test latest version of each supported ruby
- Since versions of Rails below 4.2 are now EoL, it didn't make a ton of sense for us to keep supporting it.
- Bump gem version
- Wrap interpolated raw SQL with `Arel.sql` to address Rails 5.2 deprecation warning.
- `DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "SQL_CALC_FOUND_ROWS ?.id". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql().`
- Explicitly require `active_support` module to ensure monkey patching of …

Add Support for Rails 6; Drop Support for Rails 4.2 and Below
