mavenlink/brainstem

- lib/brainstem/concerns/controller_param_management.rb
- lib/brainstem/controller_methods.rb
- spec/brainstem/concerns/controller_param_management_spec.rb
- spec/brainstem/controller_methods_spec.rb
* Infer the param model name from the controller_name, with optional overload
> Add tooling to help build Brainstem Controllers

- lib/brainstem/presenter_collection.rb
- spec/brainstem/presenter_collection_spec.rb
In MySQL, selecting only the primary id from an expensive table sort query can sometimes result in faster results.  In this PR, we start always plucking IDs, then fetching the actual results with a second query.
> Optimize queries for MySQL

- lib/brainstem/presenter_collection.rb
- spec/brainstem/presenter_collection_spec.rb
@cantino here's the change we discussed. The use case for this is if you have a filter that you want to conditionally change depending on other filters. The use case might look like this:
```ruby
filter :cool_filter, :include_params => true do |scope, opts, params|
if params[:other_filter].present?
scope
else
scope.cool_scope
end
end
```
> Add the option for filters to be passed the params

- lib/brainstem/presenter_collection.rb
- spec/brainstem/presenter_collection_spec.rb
It is possible that a search result could have id's that are not found in the scope. We are compacting the search results to protect against
that here.
/cc @cantino @jhmoore
> Compact search results if a value isn't found with the scope.  

- lib/brainstem/presenter_collection.rb
- spec/brainstem/presenter_collection_spec.rb
@cantino this updates the filters params hash to be `key => val` instead of `key => { arg: val }`.
> Have params hash be key => val instead of key => { arg: val }

- lib/brainstem/presenter.rb
- spec/brainstem/presenter_collection_spec.rb
@naiyt, how does this look?  In forward-porting your changes to Cerebellum, it seemed like we could simplify by not changing `extract_filters` at all, and instead looking into the configuration when calling a filter to see if it has requested `include_params`.  Do you see any differences between this and master, around how it handles `nil` or default filters, for example?  It seems like it'd be the same.
> Add params to filters

- lib/brainstem/api_docs.rb
- lib/brainstem/api_docs/controller.rb
- lib/brainstem/api_docs/endpoint.rb
- lib/brainstem/api_docs/presenter.rb
- spec/brainstem/api_docs/controller_spec.rb
- spec/brainstem/api_docs/endpoint_spec.rb
- spec/brainstem/api_docs/presenter_spec.rb
- spec/brainstem/api_docs_spec.rb
@robyurkowski, we wanted to be able to have the generated links skip the extension (since we put them in individual directories with middleman for pretty routes), but still want extensions on the actual filenames.  How's this look?
> Allow configuration of links independent from filenames

- spec/brainstem/api_docs/formatters/abstract_formatter_spec.rb
- spec/dummy/rails.rb
@robyurkowski, this fixes two different warnings present in the spec output.
```
*.*........................................*...........**....................*****..../Users/andrew/.rvm/gems/ruby-2.2.3@brainstem/gems/rr-1.1.2/lib/rr/injections/double_injection.rb:168: warning: removing `initialize' may cause serious problems
...................................................................................................................../Users/andrew/workspace/brainstem/spec/dummy/rails.rb:3: warning: already initialized constant FakeRailsApplication
/Users/andrew/workspace/brainstem/spec/dummy/rails.rb:3: warning: previous definition of FakeRailsApplication was here
/Users/andrew/workspace/brainstem/spec/dummy/rails.rb:4: warning: already initialized constant FakeRailsRoutesObject …
```
> Remove warnings when running specs

- lib/brainstem/presenter.rb
- lib/brainstem/presenter_validator.rb
- spec/brainstem/presenter_collection_spec.rb
- spec/brainstem/presenter_spec.rb
- spec/brainstem/presenter_validator_spec.rb
- spec/spec_helpers/presenters.rb
@robyurkowski, this helps get around the issue with many possible `brainstem_key`s.
> Validate that the brainstem_key is required on presenters that accept multiple classes

- README.md
- lib/brainstem/concerns/lookup.rb
- lib/brainstem/dsl/association.rb
- lib/brainstem/dsl/field.rb
- lib/brainstem/presenter.rb
- spec/brainstem/dsl/association_spec.rb
- spec/brainstem/dsl/field_spec.rb
- spec/brainstem/presenter_spec.rb
- spec/spec_helpers/presenters.rb
This PR allows fields and associations to define a lookup option in order to generate a lookup cache which will run once for all the models presented. When a model is presented, who's field/association defines a lookup option, it will refer to the cache to find its value rather than redoing the work.
```
fields do
field :complicated_field, :string,
dynamic: lambda { |model| model.complicated_query(current_user) } # This is an N + 1
#...
end
```
```
fields do
field :complicated_field, :string,
lookup: lambda { |models| ComplicatedQueryServiceObject(current_user, models).group_by { |model| model.id } } 
#...
end
```
TODO:
> Add a lookup cache option for associations and fields

- lib/brainstem/presenter.rb
- spec/brainstem/presenter_spec.rb
When a hash is passed in as a filter value, it gets striingified as shown below:
```
presenter.extract_filters({ 'owned_by' => { :ids => [2], 2 => [1] }}
returns "{ 'owned_by' => { :ids => [2], 2 => [1] }"
```
This PR fixes the issue with passing in a hash value for a filter & returns a hash rather a stringified version of the hash
> Add support for hash filter values. 

- brainstem.gemspec
- lib/brainstem/presenter.rb
- spec/brainstem/presenter_spec.rb
Right now, as an example, if you have many records with identical `updated_at` timestamps, and you sort by `updated_at`, the resulting sort will be non-deterministic, and records will randomly show up multiple times on different pages.
We are adding the primary key (descending) as a fallback tie-breaker sort to _all_ queries -- one possible worry here is that it could adversely affect performance, but we think that most databases will do the right thing if given a query of `order by id desc, id desc`.
> Fix duplicates when paginating over records sorted by non-unique values

- lib/brainstem/dsl/association.rb
- lib/brainstem/dsl/field.rb
- spec/brainstem/dsl/association_spec.rb
- spec/brainstem/dsl/field_spec.rb
@plainprogrammer ,
This PR is what we had outlined from our previous discussion [here](https://github.com/mavenlink/mavenlink/pull/6878#issuecomment-263328677). Now, if we define a `lookup` that will be ran instead of the `dynamic`. This way we do not run into the case where we are improving the performance of a field or association, adding a `lookup`, and then not having the previous specs cover the new `lookup`.
As a follow up, it might make sense to delete the old dynamics, thoughts?
I made a mavenlink PR just, just to see if we get a passing build on Circle CI 
https://github.com/mavenlink/mavenlink/pull/7141
cc. @shirish-pampoorickal
> Refactor lookup to take precendece over dynamic lambda

- CHANGELOG.md
- lib/brainstem/dsl/association.rb
- lib/brainstem/dsl/associations_block.rb
- lib/brainstem/dsl/base_block.rb
- lib/brainstem/dsl/conditional.rb
- lib/brainstem/dsl/conditionals_block.rb
- lib/brainstem/dsl/field.rb
- lib/brainstem/dsl/fields_block.rb
- lib/brainstem/version.rb
- spec/brainstem/concerns/presenter_dsl_spec.rb
- spec/brainstem/dsl/association_spec.rb
- spec/brainstem/dsl/conditional_spec.rb
- spec/brainstem/dsl/field_spec.rb
- spec/brainstem/presenter_validator_spec.rb
- spec/spec_helpers/presenters.rb
- Allows specifying the description for conditionals, fields and associations with the info option
- Support legacy description param as a string
- Throw a deprecation warning when description param is specified as a string
```
conditionals do
model   :title_is_hello, lambda { workspace.title == 'hello' }, 'visible when the title is hello'
request :user_is_bob, lambda { current_user.username == 'bob' }, 'visible only to bob'
end
```
```
conditionals do
model   :title_is_hello, lambda { workspace.title == 'hello' }, info: 'visible when the title is hello'
request :user_is_bob, lambda { current_user.username == 'bob' }, info: 'visible only to bob'
end
```
> Deprecate description param as a string. Going forward the `info` option will be used for the description

- brainstem.gemspec
- lib/brainstem/query_strategies/base_strategy.rb
- lib/brainstem/query_strategies/filter_and_search.rb
- lib/brainstem/query_strategies/filter_or_search.rb
- spec/brainstem/query_strategies/filter_and_search_spec.rb
- spec/spec_helper.rb
Filter And Search was clobbering the order of search results in two places.
Initially it would:
1. Run search and get `ordered_search_ids`
2. Instantiate a scope with `scope.where(id: ordered_search_ids)`
3. Apply filters
4. Apply at least a default ordering
5. Return the models to the frontend
2 and 4 would destroy the order of relevancy that ElasticSearch returned.
This PR determines whether or not the user wants to `order` their search results based on their params. In the case that the user does want order, it imposes that order.
Otherwise, it searches, filters the results, and then reorders them using the `ordered_search_ids`.
Related to https://github.com/mavenlink/mavenlink/pull/9184
> Fix Filter and Search

- CHANGELOG.md
- README.md
- lib/brainstem/presenter_collection.rb
- lib/brainstem/query_strategies/base_strategy.rb
- lib/brainstem/version.rb
- spec/brainstem/presenter_collection_spec.rb
- spec/brainstem/query_strategies/filter_and_search_spec.rb
- spec/brainstem/query_strategies/filter_or_search_spec.rb
- spec/shared/base_strategy.rb
RFC -> https://github.com/mavenlink/rfc/pull/28
Bigmaven PR -> https://github.com/mavenlink/mavenlink/pull/10740
Brainstem-js PR -> https://github.com/mavenlink/brainstem-js/pull/121
Brainstem-redux PR -> https://github.com/mavenlink/brainstem-redux/pull/55
Adds pagination information to API responses. Currently deciding between doing this or calculating this client-side. Client-side calculations are doable, but require holding on to some state (what `perPage` and `page` the requests were made with).
> Add Pagination data to API responses

- CHANGELOG.md
- lib/brainstem/api_docs.rb
- lib/brainstem/api_docs/introspectors/rails_introspector.rb
- lib/brainstem/cli/generate_api_docs_command.rb
- lib/brainstem/version.rb
- spec/brainstem/api_docs/introspectors/rails_introspector_spec.rb
- spec/brainstem/api_docs_spec.rb
- spec/brainstem/cli/generate_api_docs_command_spec.rb
- spec/dummy/rails.rb
Allow configuration of where to get routes from. Normally this will be Rails.application. However, we should also be able to configure an engine such as `Api::Engine`.
> Bugfix engine support

- lib/brainstem/api_docs/formatters/open_api_specification/version_2/endpoint/response_definitions_formatter.rb
- lib/brainstem/api_docs/formatters/open_api_specification/version_2/presenter_formatter.rb
- lib/brainstem/dsl/association.rb
- spec/brainstem/api_docs/formatters/open_api_specification/version_2/endpoint/response_definitions_formatter_spec.rb
- spec/brainstem/api_docs/formatters/open_api_specification/version_2/presenter_formatter_spec.rb
- spec/brainstem/dsl/association_spec.rb
- Associations supported are `has_many`, `has_one`, `belongs_to` as well as `polymorphic` associations
Signed-off-by: Dor Dan <ddan@mavenlink.com>
> Generate documentation from associations

- lib/brainstem/api_docs/atlas.rb
- lib/brainstem/api_docs/controller.rb
- lib/brainstem/api_docs/controller_collection.rb
- lib/brainstem/api_docs/endpoint.rb
- lib/brainstem/api_docs/endpoint_collection.rb
- lib/brainstem/api_docs/formatters/open_api_specification/version_2/presenter_formatter.rb
- lib/brainstem/api_docs/presenter.rb
- lib/brainstem/api_docs/presenter_collection.rb
- lib/brainstem/api_docs/sinks/open_api_specification_sink.rb
- lib/brainstem/cli/generate_api_docs_command.rb
- lib/brainstem/concerns/controller_dsl.rb
- lib/brainstem/concerns/presenter_dsl.rb
- lib/brainstem/dsl/association.rb
- spec/brainstem/api_docs/controller_spec.rb
- spec/brainstem/api_docs/endpoint_spec.rb
- spec/brainstem/api_docs/formatters/open_api_specification/version_2/presenter_formatter_spec.rb
- spec/brainstem/api_docs/presenter_spec.rb
- spec/brainstem/cli/generate_api_docs_command_spec.rb
- spec/brainstem/concerns/controller_dsl_spec.rb
- spec/brainstem/concerns/presenter_dsl_spec.rb
- spec/brainstem/dsl/association_spec.rb
- Add ability to add an internal option to all properties
- When properties are marked as internal, docs will not be generated for them unless `--include-internal` is passed via the CLI.
- Add the ability to describe why an endpoint is marked as `internal` or `nodoc!`.
> Add `--include-internal` option to CLI tool.

- spec/spec_helpers/schema.rb
- Brainstem implicitly relies on the ONLY_FULL_GROUP_BY
config not being set in MySQL. Newer versions of MySQL
have this enabled by default.
- Not sure why we would suddenly start breaking. It's possible
the MySQL version in CI is not locked down.
> Fix MySQL specs

- CHANGELOG.md
- lib/brainstem/api_docs/introspectors/rails_introspector.rb
- lib/brainstem/presenter.rb
- lib/brainstem/version.rb
- spec/dummy/rails.rb
- Fetching http methods from routes in the Rails introspector has been updated to support the differences in API between Rails 4.x & 5.x
- Fix deprecation warnings for Rails 6
> Add Rails 5.x support

- Gemfile.lock
- gemfiles/activerecord4_2.gemfile.lock
- gemfiles/activerecord5_0.gemfile.lock
- gemfiles/activerecord5_1.gemfile.lock
- gemfiles/activerecord5_2.gemfile.lock
- gemfiles/activerecord6_0.gemfile.lock
- lib/brainstem/presenter.rb
- lib/brainstem/version.rb
- spec/brainstem/presenter_spec.rb
- Wrap interpolated raw SQL with `Arel.sql` to address Rails 5.2 deprecation warning.
- `DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "COALECE(tasks.name, tasks.created_at) asc". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from apply_ordering_to_scope at ../workspace/brainstem/lib/brainstem/presenter.rb:217)`
> Resolve Rails 5.2 deprecation warning for passing raw sql to reorder

- lib/brainstem/api_docs/formatters/open_api_specification/version_2/field_definitions/response_field_formatter.rb
- spec/brainstem/api_docs/formatters/open_api_specification/version_2/field_definitions/response_field_formatter_spec.rb
Enums are a legal part of the OAS data format. Brainstem does not allow a way for controllers / parameters to provide these enums though, so this PR is used to expose them.
https://swagger.io/docs/specification/data-models/enums/
By way of example, if the `access_level` in Workspaces:particpations is used as an enum, the only code change necessary is adding the `enum` key with the legal values in an array. The `type` of the field is still respected.
```ruby
participant.valid :access, :string,
enum: %w(collaboration time_logging financial admin),
info: <<~INFO
The access level of the participant. Must be one of the following: `collaboration`,
`time_logging`, `financial` or `admin`.
INFO
```
This generates the api documentation:
And finally the OAS Schema yml file:
```yml
participations: …
```
> Allow enums to be reflected in OAS generation

- lib/brainstem/concerns/presenter_dsl.rb
- lib/brainstem/presenter.rb
- lib/brainstem/query_strategies/base_strategy.rb
- lib/brainstem/version.rb
- spec/brainstem/presenter_collection_spec.rb
- spec/brainstem/presenter_spec.rb
- spec/spec_helpers/db.rb
- spec/spec_helpers/presenters.rb
- spec/spec_helpers/schema.rb
In BigMaven we need to cache the count value for `line_items` queries because getting the count is 90% of the compute time for each request. Since the use case is to paginate over all requests within a relatively short amount of time we can get the count and cache it in bigmaven. But we need brainstem to skip calculating the count.
> Allow presenters to override count and id calculation from scope

- CHANGELOG.md
- Gemfile.lock
- lib/brainstem/concerns/presenter_dsl.rb
- lib/brainstem/presenter.rb
- lib/brainstem/query_strategies/base_strategy.rb
- lib/brainstem/version.rb
- spec/brainstem/concerns/presenter_dsl_spec.rb
- spec/brainstem/presenter_spec.rb
- spec/spec_helpers/presenters.rb
Count evaluator block needs to be executed with the context of the presenter helper if one is present.
> instance_exec count_evaluator within context of presenter helper
